[package]
name = "xenolith"
description = "Static recompiler turning Xbox 360 executables into native code"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
miette = { version = "7.6.0", features = ["fancy"] }
xenolith-analysis = { version = "0.1.0", path = "../xenolith-analysis" }
xenolith-lift = { version = "0.1.0", path = "../xenolith-lift" }
xenolith-ppc = { version = "0.1.0", path = "../xenolith-ppc" }
xenolith-xex = { version = "0.1.0", path = "../xenolith-xex" }

[lints]
workspace = true
