[package]
name = "xenolith-xex"
description = "Parser and decoder for Xbox 360 XEX executable containers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
aes = "0.9.2"
cbc = { version = "0.2.1", features = ["block-padding"] }
thiserror = "2.0.20"

[lints]
workspace = true
