[package]
name = "xenolith-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
xenolith-xex = { version = "0.1.0", path = ".." }

[[bin]]
name = "container"
path = "fuzz_targets/container.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode"
path = "fuzz_targets/decode.rs"
test = false
doc = false
bench = false
